In [285]:
#importing pandas as pd
import pandas as pd
  
# Read and store content
# of an excel file 
read_file = pd.read_excel ("Yamunapuram.xlsx")
  
# Write the dataframe object
# into csv file
read_file.to_csv ("Ypm.csv", 
                  index = None,
                  header=True)
    
# read csv file and convert 
# into a dataframe object
#skippingheaders
df = pd.DataFrame(pd.read_csv("Ypm.csv", skiprows=16))


# Remove three columns as index base
df.drop(df.columns[[1,3,4,5,6,7,8]], axis = 1, inplace = True)

  
# show the dataframe
df

# pest = df.iloc[:,0]
# print(pest)

             From Date  PM2.5
0     01-01-2017 00:00   None
1     02-01-2017 00:00   None
2     03-01-2017 00:00   None
3     04-01-2017 00:00   None
4     05-01-2017 00:00   None
...                ...    ...
1668  27-07-2021 00:00  31.51
1669  28-07-2021 00:00  12.74
1670  29-07-2021 00:00  25.04
1671  30-07-2021 00:00  14.67
1672  31-07-2021 00:00  10.08

[1673 rows x 2 columns]

In [286]:
x = df.iloc[0,0]
i1 = x.rfind('-')
i2 = x.find(' ')

year = int(x[i1+1:i2])
print(year)

i3 = x.find('-')
i4 = x.rfind('-')

month = int(x[i3+1:i4])
print(month)

2017
1

In [287]:
l_df = df.shape[0]
ms= []
ys = []

for i in range(l_df):
    x = df.iloc[i,0]
    i1 = x.rfind('-')
    i2 = x.find(' ')

    year = x[i1+1:i2]
    
    i3 = x.find('-')
    i4 = x.rfind('-')

    month = x[i3+1:i4]
    
    ms.append(month)
    ys.append(year)
    
df["Month"] = ms
df["Year"] = ys
df

             From Date  PM2.5 Month  Year
0     01-01-2017 00:00   None    01  2017
1     02-01-2017 00:00   None    01  2017
2     03-01-2017 00:00   None    01  2017
3     04-01-2017 00:00   None    01  2017
4     05-01-2017 00:00   None    01  2017
...                ...    ...   ...   ...
1668  27-07-2021 00:00  31.51    07  2021
1669  28-07-2021 00:00  12.74    07  2021
1670  29-07-2021 00:00  25.04    07  2021
1671  30-07-2021 00:00  14.67    07  2021
1672  31-07-2021 00:00  10.08    07  2021

[1673 rows x 4 columns]

In [288]:
df.columns

Index(['From Date', 'PM2.5', 'Month', 'Year'], dtype='object')

In [289]:
l1 = []
l2 = []

for i in range(12):
    if i < 9:
        el = "0" + str(i+1)
    else:
        el = str(i+1)
    l1.append(el)
    
for i in range(2017, 2022):
    l2.append(str(i))

In [290]:
dict_temp = {}
for el2 in l2:
    for el1 in l1:
        df_temp1 = df[df["Year"] == el2]
        df_temp2 = df_temp1[df_temp1["Month"] == el1]
        
        x1 = df_temp2.shape[0]
        x2 = 0
        x3 = 0
        for i in range(x1):
            if df_temp2.iat[i, 1] == "None":
                x3 = x3 + 1
                continue
            else:
                x2 = x2 + float(df_temp2.iat[i, 1])
        list_temp = [x1, x2, x3]
        st_temp = "MY-" + el1 + "-"+el2
        dict_temp[st_temp] = list_temp

In [291]:
dict_temp

{'MY-01-2017': [31, 0, 31],
 'MY-02-2017': [28, 0, 28],
 'MY-03-2017': [31, 0, 31],
 'MY-04-2017': [30, 0, 30],
 'MY-05-2017': [31, 0, 31],
 'MY-06-2017': [30, 0, 30],
 'MY-07-2017': [31, 0, 31],
 'MY-08-2017': [31, 0, 31],
 'MY-09-2017': [30, 0, 30],
 'MY-10-2017': [31, 0, 31],
 'MY-11-2017': [30, 0, 30],
 'MY-12-2017': [31, 0, 31],
 'MY-01-2018': [31, 0, 31],
 'MY-02-2018': [28, 0, 28],
 'MY-03-2018': [31, 0, 31],
 'MY-04-2018': [30, 0, 30],
 'MY-05-2018': [31, 1088.2, 18],
 'MY-06-2018': [30, 1893.4500000000003, 0],
 'MY-07-2018': [31, 1001.57, 2],
 'MY-08-2018': [31, 898.3599999999997, 2],
 'MY-09-2018': [30, 1274.99, 0],
 'MY-10-2018': [31, 4377.8099999999995, 0],
 'MY-11-2018': [30, 6439.2199999999975, 0],
 'MY-12-2018': [31, 7664.929999999999, 0],
 'MY-01-2019': [31, 6036.26, 0],
 'MY-02-2019': [28, 3251.3700000000003, 0],
 'MY-03-2019': [31, 2570.540000000001, 2],
 'MY-04-2019': [30, 2517.4700000000003, 0],
 'MY-05-2019': [31, 2587.51, 0],
 'MY-06-2019': [30, 1358.52, 6],
 'MY-07-2019': [31, 1084.29, 3],
 'MY-08-2019': [31, 852.9399999999998, 2],
 'MY-09-2019': [30, 800.3299999999999, 1],
 'MY-10-2019': [31, 2453.82, 7],
 'MY-11-2019': [30, 4050.0, 0],
 'MY-12-2019': [31, 4956.200000000001, 3],
 'MY-01-2020': [31, 4570.950000000001, 0],
 'MY-02-2020': [29, 3486.5200000000004, 0],
 'MY-03-2020': [31, 1842.05, 0],
 'MY-04-2020': [30, 1692.9700000000003, 0],
 'MY-05-2020': [31, 1786.3700000000001, 0],
 'MY-06-2020': [30, 1390.23, 0],
 'MY-07-2020': [31, 889.9599999999998, 0],
 'MY-08-2020': [31, 601.45, 0],
 'MY-09-2020': [30, 1552.8500000000001, 0],
 'MY-10-2020': [31, 4505.72, 0],
 'MY-11-2020': [30, 6678.120000000002, 0],
 'MY-12-2020': [31, 7001.32, 0],
 'MY-01-2021': [31, 5719.2300000000005, 0],
 'MY-02-2021': [28, 3982.8200000000006, 0],
 'MY-03-2021': [31, 3039.0299999999993, 0],
 'MY-04-2021': [30, 2396.16, 0],
 'MY-05-2021': [31, 1576.2300000000002, 0],
 'MY-06-2021': [30, 1222.77, 0],
 'MY-07-2021': [31, 923.2899999999998, 0],
 'MY-08-2021': [0, 0, 0],
 'MY-09-2021': [0, 0, 0],
 'MY-10-2021': [0, 0, 0],
 'MY-11-2021': [0, 0, 0],
 'MY-12-2021': [0, 0, 0]}

In [292]:
key_list = list(dict_temp.keys())

In [293]:
for k in key_list:
    if dict_temp[k][0] - dict_temp[k][2] == 0:
        l = dict_temp[k]
        l.append(-1)
        dict_temp[k] = l
        continue
    print(dict_temp[k][0]-dict_temp[k][2])
    a = dict_temp[k][1]/(dict_temp[k][0]-dict_temp[k][2])
    l = dict_temp[k]
    l.append(a)
    dict_temp[k] = l

13
30
29
29
30
31
30
31
31
28
29
30
31
24
28
29
29
24
30
28
31
29
31
30
31
30
31
31
30
31
30
31
31
28
31
30
31
30
31

In [294]:
dict_temp

{'MY-01-2017': [31, 0, 31, -1],
 'MY-02-2017': [28, 0, 28, -1],
 'MY-03-2017': [31, 0, 31, -1],
 'MY-04-2017': [30, 0, 30, -1],
 'MY-05-2017': [31, 0, 31, -1],
 'MY-06-2017': [30, 0, 30, -1],
 'MY-07-2017': [31, 0, 31, -1],
 'MY-08-2017': [31, 0, 31, -1],
 'MY-09-2017': [30, 0, 30, -1],
 'MY-10-2017': [31, 0, 31, -1],
 'MY-11-2017': [30, 0, 30, -1],
 'MY-12-2017': [31, 0, 31, -1],
 'MY-01-2018': [31, 0, 31, -1],
 'MY-02-2018': [28, 0, 28, -1],
 'MY-03-2018': [31, 0, 31, -1],
 'MY-04-2018': [30, 0, 30, -1],
 'MY-05-2018': [31, 1088.2, 18, 83.70769230769231],
 'MY-06-2018': [30, 1893.4500000000003, 0, 63.11500000000001],
 'MY-07-2018': [31, 1001.57, 2, 34.53689655172414],
 'MY-08-2018': [31, 898.3599999999997, 2, 30.977931034482747],
 'MY-09-2018': [30, 1274.99, 0, 42.49966666666667],
 'MY-10-2018': [31, 4377.8099999999995, 0, 141.2196774193548],
 'MY-11-2018': [30, 6439.2199999999975, 0, 214.6406666666666],
 'MY-12-2018': [31, 7664.929999999999, 0, 247.25580645161287],
 'MY-01-2019': [31, 6036.26, 0, 194.71806451612903],
 'MY-02-2019': [28, 3251.3700000000003, 0, 116.12035714285716],
 'MY-03-2019': [31, 2570.540000000001, 2, 88.63931034482762],
 'MY-04-2019': [30, 2517.4700000000003, 0, 83.91566666666668],
 'MY-05-2019': [31, 2587.51, 0, 83.46806451612903],
 'MY-06-2019': [30, 1358.52, 6, 56.605],
 'MY-07-2019': [31, 1084.29, 3, 38.724642857142854],
 'MY-08-2019': [31, 852.9399999999998, 2, 29.411724137931028],
 'MY-09-2019': [30, 800.3299999999999, 1, 27.597586206896548],
 'MY-10-2019': [31, 2453.82, 7, 102.2425],
 'MY-11-2019': [30, 4050.0, 0, 135.0],
 'MY-12-2019': [31, 4956.200000000001, 3, 177.0071428571429],
 'MY-01-2020': [31, 4570.950000000001, 0, 147.45000000000002],
 'MY-02-2020': [29, 3486.5200000000004, 0, 120.22482758620691],
 'MY-03-2020': [31, 1842.05, 0, 59.420967741935485],
 'MY-04-2020': [30, 1692.9700000000003, 0, 56.43233333333334],
 'MY-05-2020': [31, 1786.3700000000001, 0, 57.62483870967743],
 'MY-06-2020': [30, 1390.23, 0, 46.341],
 'MY-07-2020': [31, 889.9599999999998, 0, 28.70838709677419],
 'MY-08-2020': [31, 601.45, 0, 19.401612903225807],
 'MY-09-2020': [30, 1552.8500000000001, 0, 51.76166666666667],
 'MY-10-2020': [31, 4505.72, 0, 145.3458064516129],
 'MY-11-2020': [30, 6678.120000000002, 0, 222.60400000000007],
 'MY-12-2020': [31, 7001.32, 0, 225.8490322580645],
 'MY-01-2021': [31, 5719.2300000000005, 0, 184.49129032258065],
 'MY-02-2021': [28, 3982.8200000000006, 0, 142.24357142857144],
 'MY-03-2021': [31, 3039.0299999999993, 0, 98.0332258064516],
 'MY-04-2021': [30, 2396.16, 0, 79.872],
 'MY-05-2021': [31, 1576.2300000000002, 0, 50.84612903225807],
 'MY-06-2021': [30, 1222.77, 0, 40.759],
 'MY-07-2021': [31, 923.2899999999998, 0, 29.78354838709677],
 'MY-08-2021': [0, 0, 0, -1],
 'MY-09-2021': [0, 0, 0, -1],
 'MY-10-2021': [0, 0, 0, -1],
 'MY-11-2021': [0, 0, 0, -1],
 'MY-12-2021': [0, 0, 0, -1]}

In [295]:
#to get the particular month with the year 
final_l0 = key_list[:-5]
final_l1 = []
for f in final_l0:
    f1 = f[3:]
    final_l1.append(f1)
final_l1

['01-2017',
 '02-2017',
 '03-2017',
 '04-2017',
 '05-2017',
 '06-2017',
 '07-2017',
 '08-2017',
 '09-2017',
 '10-2017',
 '11-2017',
 '12-2017',
 '01-2018',
 '02-2018',
 '03-2018',
 '04-2018',
 '05-2018',
 '06-2018',
 '07-2018',
 '08-2018',
 '09-2018',
 '10-2018',
 '11-2018',
 '12-2018',
 '01-2019',
 '02-2019',
 '03-2019',
 '04-2019',
 '05-2019',
 '06-2019',
 '07-2019',
 '08-2019',
 '09-2019',
 '10-2019',
 '11-2019',
 '12-2019',
 '01-2020',
 '02-2020',
 '03-2020',
 '04-2020',
 '05-2020',
 '06-2020',
 '07-2020',
 '08-2020',
 '09-2020',
 '10-2020',
 '11-2020',
 '12-2020',
 '01-2021',
 '02-2021',
 '03-2021',
 '04-2021',
 '05-2021',
 '06-2021',
 '07-2021']

In [296]:
final_l2 = []
final_l3 = []
for i in final_l0:
    if dict_temp[i][0] == 0:
        new = 0
    else:
        new = round((dict_temp[i][2]/dict_temp[i][0])*100, 2)
    final_l3.append(new)
    if dict_temp[i][3] == -1:
        final_l2.append(0)
    else:
        final_l2.append(dict_temp[i][3])
        
dict_f = {"Dates": final_l1, "PM2.5": final_l2, "Missing Days": final_l3}
df_f = pd.DataFrame(dict_f)
#to get the monthly average concentration of PM 2.5       
df_f.to_csv("Ypm_final.csv",
                index = None,
                header = True)

In [223]:
def addlabels(x,y):
    for i in range(len(x)):
        plt.text(i, y[i], y[i], ha = 'center')

In [198]:
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
figure(figsize=(8, 6), dpi=80)
plt.bar(final_l1[0:12], final_l2[0:12])
plt.xticks(rotation=90)
plt.xlabel("Month", fontsize = 20)
plt.ylabel("PM 2.5", fontsize = 20)
plt.title("Vasundhara - 2017", fontsize = 20)
addlabels(final_l1[0:12], final_l3[0:12])

ValueError: Image size of 581x329741 pixels is too large. It must be less than 2^16 in each direction.

In [ ]:
figure(figsize=(8, 6), dpi=80)
plt.bar(final_l1[12:24], final_l2[12:24])
plt.xticks(rotation=90)
plt.xlabel("Month", fontsize = 20)
plt.ylabel("PM 2.5", fontsize = 20)
plt.title("Vasundhara - 2018", fontsize = 20)
addlabels(final_l1[12:24], final_l3[12:24])

In [ ]:
figure(figsize=(8, 6), dpi=80)
plt.bar(final_l1[24:36], final_l2[24:36])
plt.xticks(rotation=90)
plt.xlabel("Month", fontsize = 20)
plt.ylabel("PM 2.5", fontsize = 20)
plt.title("Vasundhara- 2019", fontsize = 20)
addlabels(final_l1[24:36], final_l3[24:36])

In [ ]:
figure(figsize=(8, 6), dpi=80)
plt.bar(final_l1[36:48], final_l2[36:48])
plt.xticks(rotation=90)
plt.xlabel("Month", fontsize = 20)
plt.ylabel("PM 2.5", fontsize = 20)
plt.title("Vasundhara - 2020", fontsize = 20)
addlabels(final_l1[36:48], final_l3[36:48])

In [ ]:
figure(figsize=(8, 6), dpi=80)
plt.bar(final_l1[48:55], final_l2[48:55])
plt.xticks(rotation=90)
plt.xlabel("Month", fontsize = 20)
plt.ylabel("PM 2.5", fontsize = 20)
plt.title("Vasundhara - 2021", fontsize = 20)
addlabels(final_l1[48:55], final_l3[48:55])